name: quasar
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  test: ^1.17.12
dependencies: 
  pedantic: ^1.9.0
  dart_nats: ^0.6.1
  uuid: ^3.0.7
